cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ROOT OR NOT DEFINED BINARY_DIR OR NOT DEFINED ZANIDE)
  message(FATAL_ERROR "run_frame_budget.cmake requires ROOT, BINARY_DIR, and ZANIDE")
endif()

if(NOT EXISTS "${ZANIDE}")
  message("FRAME_BUDGET_SKIPPED: ZanIDE executable does not exist: ${ZANIDE}")
  return()
endif()

set(_run "${BINARY_DIR}/frame_budget_run")
file(REMOVE_RECURSE "${_run}")
file(MAKE_DIRECTORY "${_run}")
file(MAKE_DIRECTORY "${_run}/uidrv")

file(TO_CMAKE_PATH "${ROOT}/tests/perf/ide_hover_scroll.uidrv" _script)
file(TO_CMAKE_PATH "${_run}/uidrv" _uidrv_out)
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env
    "ZAN_FRAME_PROF=1"
    "ZAN_UI_SCRIPT=${_script}"
    "ZAN_UI_OUT=${_uidrv_out}"
    "${ZANIDE}"
  WORKING_DIRECTORY "${_run}"
  TIMEOUT 180
  RESULT_VARIABLE _run_rc
  OUTPUT_FILE "${_run}/stdout.log"
  ERROR_FILE "${_run}/stderr.log")

if(_run_rc MATCHES "timeout")
  execute_process(
    COMMAND taskkill /F /T /IM ZanIDE.exe
    OUTPUT_QUIET ERROR_QUIET
    RESULT_VARIABLE _kill_rc)
  message(FATAL_ERROR "ZanIDE timed out after 180 seconds; residual cleanup rc=${_kill_rc}")
endif()

if(NOT EXISTS "${_run}/uidrv/results.log")
  message(FATAL_ERROR "UiDriver results.log was not produced (rc=${_run_rc})")
endif()
file(READ "${_run}/uidrv/results.log" _results)
string(REPLACE "\r\n" "\n" _results "${_results}")
if(NOT _results MATCHES "quit")
  message(FATAL_ERROR "UiDriver results.log does not contain quit (rc=${_run_rc})")
endif()
if(NOT _results MATCHES "DONE")
  message(FATAL_ERROR "UiDriver results.log does not contain DONE (rc=${_run_rc})")
endif()
if(NOT _run_rc EQUAL 0)
  message(FATAL_ERROR "ZanIDE exited with rc=${_run_rc} after UiDriver completion")
endif()

if(NOT EXISTS "${_run}/zan_frame_perf.log")
  message(FATAL_ERROR "zan_frame_perf.log was not produced (rc=${_run_rc})")
endif()
file(READ "${_run}/zan_frame_perf.log" _log)
string(REPLACE "\r\n" "\n" _log "${_log}")
string(REPLACE "\n" ";" _lines "${_log}")

set(_first_count 0)
set(_frame_count 0)
set(_frame_indexes "")
list(LENGTH _lines _line_count)
math(EXPR _last_line "${_line_count} - 1")
foreach(_i RANGE 0 ${_last_line})
  list(GET _lines ${_i} _line)
  if(_line MATCHES "^firstframe ")
    math(EXPR _first_count "${_first_count} + 1")
    set(_first_line "${_line}")
  endif()
  if(_line MATCHES "^frames=30 ")
    math(EXPR _frame_count "${_frame_count} + 1")
    list(APPEND _frame_indexes "${_i}")
  endif()
endforeach()

if(_frame_count LESS 6)
  message(FATAL_ERROR "frame log has only ${_frame_count} frames=30 batches; need at least 6")
endif()
if(NOT _first_count EQUAL 1)
  message(FATAL_ERROR "frame log has ${_first_count} firstframe lines; need exactly 1")
endif()

file(STRINGS "${ROOT}/tests/perf/frame_budget.txt" _budget_lines
  REGEX "^[A-Za-z_]+=[0-9]+$")
foreach(_budget_line ${_budget_lines})
  string(REGEX MATCH "^([^=]+)=([0-9]+)$" _budget_match "${_budget_line}")
  set("_budget_${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
endforeach()
foreach(_required blend_kpx restore_kpx fill_kpx round_kpx grad_kpx
                 total_kpx style_resolve style_miss render_ms worst_ms tree_ms
                 surface_w surface_h first_whole_ms first_tree_ms
                 first_blend_kpx first_style_miss)
  if(NOT DEFINED "_budget_${_required}")
    message(FATAL_ERROR "frame budget is missing ${_required}")
  endif()
endforeach()

function(_field LINE KEY DEFAULT OUT)
  string(REGEX MATCH "${KEY}=([0-9]+(\\.[0-9]+)?)" _field_match "${LINE}")
  if(_field_match)
    set(${OUT} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    set(${OUT} "${DEFAULT}" PARENT_SCOPE)
  endif()
endfunction()

function(_raster_kpx LINE KEY OUT)
  string(REGEX MATCH "${KEY}=[^/ ]*/([0-9]+)kpx" _raster_match "${LINE}")
  if(_raster_match)
    set(${OUT} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    set(${OUT} "0" PARENT_SCOPE)
  endif()
endfunction()

_field("${_first_line}" "whole_ms" "0" _first_whole)
_field("${_first_line}" "render_ms" "0" _first_render)
_field("${_first_line}" "tree_ms" "0" _first_tree)
_field("${_first_line}" "blend" "0" _first_blend)

string(REGEX MATCH "style=([0-9]+)/([0-9]+)miss" _first_style_match "${_first_line}")
if(_first_style_match)
  set(_first_style_miss "${CMAKE_MATCH_2}")
else()
  set(_first_style_miss "0")
endif()

set(_max_blend 0)
set(_max_restore 0)
set(_max_fill 0)
set(_max_round 0)
set(_max_grad 0)
set(_max_total 0)
set(_max_style 0)
set(_max_miss 0)
set(_max_render 0)
set(_max_worst 0)
set(_max_tree 0)
list(LENGTH _frame_indexes _batch_count)
math(EXPR _steady_start "2")
if(_batch_count LESS 3)
  message(FATAL_ERROR "no steady-state frame batches remain after dropping two")
endif()
math(EXPR _last_batch "${_batch_count} - 1")
foreach(_batch RANGE ${_steady_start} ${_last_batch})
  list(GET _frame_indexes ${_batch} _frame_index)
  math(EXPR _raster_index "${_frame_index} + 1")
  if(_raster_index GREATER_EQUAL _line_count)
    message(FATAL_ERROR "frames=30 at line ${_frame_index} has no following raster/frame line")
  endif()
  list(GET _lines ${_frame_index} _frame_line)
  list(GET _lines ${_raster_index} _raster_line)
  if(NOT _raster_line MATCHES "raster/frame ")
    message(FATAL_ERROR "frames=30 at line ${_frame_index} is not followed by raster/frame")
  endif()
  string(REGEX MATCH "surface=([0-9]+)x([0-9]+)" _surface_match "${_frame_line}")
  if(NOT _surface_match)
    string(REGEX MATCH "surface=([0-9]+)x([0-9]+)" _surface_match "${_raster_line}")
  endif()
  if(NOT _surface_match)
    message(FATAL_ERROR "steady-state frames=30 at line ${_frame_index} has no surface size")
  endif()
  set(_batch_surface_w "${CMAKE_MATCH_1}")
  set(_batch_surface_h "${CMAKE_MATCH_2}")
  if(NOT _surface_seen)
    set(_surface_width "${_batch_surface_w}")
    set(_surface_height "${_batch_surface_h}")
    set(_surface_seen TRUE)
  elseif(NOT _batch_surface_w EQUAL _surface_width OR
         NOT _batch_surface_h EQUAL _surface_height)
    set(_surface_mismatch TRUE)
  endif()
  _raster_kpx("${_raster_line}" "fill" _fill)
  _raster_kpx("${_raster_line}" "blend" _blend)
  _raster_kpx("${_raster_line}" "round" _round)
  _raster_kpx("${_raster_line}" "grad" _grad)
  _raster_kpx("${_raster_line}" "restore" _restore)
  _raster_kpx("${_raster_line}" "glyph" _glyph)
  _raster_kpx("${_raster_line}" "snap" _snap)
  string(REGEX MATCH "style=([0-9]+)/([0-9]+)miss" _style_match "${_raster_line}")
  if(_style_match)
    set(_style "${CMAKE_MATCH_1}")
    set(_miss "${CMAKE_MATCH_2}")
  else()
    set(_style "0")
    set(_miss "0")
  endif()
  _field("${_frame_line}" "render_ms" "0" _render)
  _field("${_frame_line}" "worst_ms" "0" _worst)
  _field("${_frame_line}" "tree_ms" "0" _tree)
  math(EXPR _total "${_fill} + ${_blend} + ${_round} + ${_grad} + ${_restore} + ${_glyph} + ${_snap}")
  if(_blend GREATER _max_blend)
    set(_max_blend "${_blend}")
  endif()
  if(_restore GREATER _max_restore)
    set(_max_restore "${_restore}")
  endif()
  if(_fill GREATER _max_fill)
    set(_max_fill "${_fill}")
  endif()
  if(_round GREATER _max_round)
    set(_max_round "${_round}")
  endif()
  if(_grad GREATER _max_grad)
    set(_max_grad "${_grad}")
  endif()
  if(_total GREATER _max_total)
    set(_max_total "${_total}")
  endif()
  if(_style GREATER _max_style)
    set(_max_style "${_style}")
  endif()
  if(_miss GREATER _max_miss)
    set(_max_miss "${_miss}")
  endif()
  if(_render GREATER _max_render)
    set(_max_render "${_render}")
  endif()
  if(_worst GREATER _max_worst)
    set(_max_worst "${_worst}")
  endif()
  if(_tree GREATER _max_tree)
    set(_max_tree "${_tree}")
  endif()
endforeach()

message("FRAME_BUDGET measured vs budget")
message("  surface      ${_surface_width}x${_surface_height} / ${_budget_surface_w}x${_budget_surface_h}")
if(_surface_mismatch OR
   NOT _surface_width EQUAL _budget_surface_w OR
   NOT _surface_height EQUAL _budget_surface_h)
  message("FRAME_BUDGET_SKIPPED: surface ${_surface_width}x${_surface_height} does not match expected ${_budget_surface_w}x${_budget_surface_h}")
  return()
endif()
message("  blend_kpx    ${_max_blend} / ${_budget_blend_kpx}")
message("  restore_kpx  ${_max_restore} / ${_budget_restore_kpx}")
message("  fill_kpx     ${_max_fill} / ${_budget_fill_kpx}")
message("  round_kpx    ${_max_round} / ${_budget_round_kpx}")
message("  grad_kpx     ${_max_grad} / ${_budget_grad_kpx}")
message("  total_kpx    ${_max_total} / ${_budget_total_kpx}")
message("  style_resolve ${_max_style} / ${_budget_style_resolve}")
message("  style_miss   ${_max_miss} / ${_budget_style_miss}")
message("  render_ms    ${_max_render} / ${_budget_render_ms}")
message("  worst_ms     ${_max_worst} / ${_budget_worst_ms}")
message("  tree_ms      ${_max_tree} / ${_budget_tree_ms}")
message("  first_whole_ms ${_first_whole} / ${_budget_first_whole_ms}")
message("  first_tree_ms  ${_first_tree} / ${_budget_first_tree_ms}")
message("  first_blend_kpx ${_first_blend} / ${_budget_first_blend_kpx}")
message("  first_style_miss ${_first_style_miss} / ${_budget_first_style_miss}")

set(_failed "")
foreach(_check
    "blend_kpx;${_max_blend};${_budget_blend_kpx}"
    "restore_kpx;${_max_restore};${_budget_restore_kpx}"
    "fill_kpx;${_max_fill};${_budget_fill_kpx}"
    "round_kpx;${_max_round};${_budget_round_kpx}"
    "grad_kpx;${_max_grad};${_budget_grad_kpx}"
    "total_kpx;${_max_total};${_budget_total_kpx}"
    "style_resolve;${_max_style};${_budget_style_resolve}"
    "style_miss;${_max_miss};${_budget_style_miss}"
    "render_ms;${_max_render};${_budget_render_ms}"
    "worst_ms;${_max_worst};${_budget_worst_ms}"
    "tree_ms;${_max_tree};${_budget_tree_ms}"
    "first_whole_ms;${_first_whole};${_budget_first_whole_ms}"
    "first_tree_ms;${_first_tree};${_budget_first_tree_ms}"
    "first_blend_kpx;${_first_blend};${_budget_first_blend_kpx}"
    "first_style_miss;${_first_style_miss};${_budget_first_style_miss}")
  list(GET _check 0 _name)
  list(GET _check 1 _value)
  list(GET _check 2 _limit)
  if(_value GREATER _limit)
    list(APPEND _failed "${_name}=${_value} (budget ${_limit})")
  endif()
endforeach()
if(_failed)
  message(FATAL_ERROR "FRAME_BUDGET_EXCEEDED: ${_failed}")
endif()
message("FRAME_BUDGET_OK")
