cmake_policy(SET CMP0012 NEW)
if(NOT ROOT OR NOT ZANC OR NOT OUT_EXE)
  message(FATAL_ERROR "ROOT, ZANC and OUT_EXE are required")
endif()

# Compile the production command builders with only their environment stubbed.
# Extracting this block avoids linking the IDE's window, debugger and network.
file(READ "${ROOT}/src/ide_zan/src/services/ZanIDE.Project.zan" _project)
string(FIND "${_project}" "    static string CompileToExe(" _begin)
string(FIND "${_project}" "    /// Reads a `key = value`" _end)
if(_begin LESS 0 OR _end LESS _begin)
  message(FATAL_ERROR "IDE compile builder boundaries not found")
endif()
math(EXPR _length "${_end} - ${_begin}")
string(SUBSTRING "${_project}" ${_begin} ${_length} _builders)
get_filename_component(_out_dir "${OUT_EXE}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")
set(_generated "${_out_dir}/ide_compile_builders.zan")
file(WRITE "${_generated}" "partial class ZanIDE {\n${_builders}}\n")

# The callers must distinguish debug runs from debug deployment too.
file(READ "${ROOT}/src/ide_zan/src/shell/ZanIDE.Workspace.zan" _workspace)
string(REGEX MATCHALL "CompileToExe(SingleFile)?\\([^;]*exe, true, dbg\\)" _publish_calls "${_workspace}")
list(LENGTH _publish_calls _publish_count)
if(NOT _publish_count EQUAL 3 OR _workspace MATCHES "exe, !dbg, dbg\\)")
  message(FATAL_ERROR "Native publish callers must pass publish=true")
endif()
string(FIND "${_workspace}" "string pubFlag = IdeCompileMode.Flags(true, dbg, false);" _direct_publish)
if(_direct_publish LESS 0)
  message(FATAL_ERROR "Direct cross/library publish must use the deployment policy")
endif()
file(READ "${ROOT}/src/ide_zan/src/services/IdeJobMonitor.zan" _monitor)
if(NOT _monitor MATCHES "CompileToExe\\([^;]*ll, preparedExe, false, true\\)")
  message(FATAL_ERROR "F5 must select local debug mode")
endif()

set(SRC "${ROOT}/tests/ide/compile_mode_test.zan")
set(EXPECTED "${ROOT}/tests/ide/compile_mode_test.out")
set(WORKDIR "${ROOT}")
set(ZANC_ARGS "${_generated}" "${ROOT}/src/ide_zan/src/services/IdeCompileMode.zan"
  --auto-stdlib --arc-guard --check-leaks --strict-runtime)
include("${ROOT}/tests/run_case.cmake")
if("${run_out}${run_err}" MATCHES "ARC integrity failure|memory leak detected")
  zan_drop_artifact()
  message(FATAL_ERROR "IDE mode test memory diagnostics failed\n${run_out}${run_err}")
endif()
