if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()
file(TO_CMAKE_PATH "${ROOT}" ROOT)
set(SEED "${ROOT}/tools/mcp_server/gallery.json")
if(NOT EXISTS "${SEED}")
  message(FATAL_ERROR "gallery seed is missing: ${SEED}")
endif()
file(READ "${SEED}" seed)
string(JSON entry_count LENGTH "${seed}" entries)
math(EXPR last_entry "${entry_count} - 1")
set(refs "")
if(last_entry GREATER_EQUAL 0)
  foreach(i RANGE 0 ${last_entry})
    string(JSON file_count LENGTH "${seed}" entries ${i} files)
    math(EXPR last_file "${file_count} - 1")
    if(last_file GREATER_EQUAL 0)
      foreach(j RANGE 0 ${last_file})
        string(JSON ref GET "${seed}" entries ${i} files ${j})
        list(APPEND refs "${ref}")
        if(NOT EXISTS "${ROOT}/${ref}")
          message(FATAL_ERROR "gallery seed entry ${i} references missing file: ${ref}")
        endif()
      endforeach()
    endif()
  endforeach()
endif()

file(GLOB_RECURSE manifests LIST_DIRECTORIES false
  "${ROOT}/templates/*/*/template.manifest")
foreach(manifest IN LISTS manifests)
  file(READ "${manifest}" text)
  string(REGEX MATCH "(^|[\r\n])[ \t]*entry[ \t]*=[ \t]*([^\r\n]+)" match "${text}")
  if(NOT match)
    message(FATAL_ERROR "template manifest has no entry=: ${manifest}")
  endif()
  string(REGEX REPLACE ".*entry[ \t]*=[ \t]*" "" entry "${match}")
  string(STRIP "${entry}" entry)
  get_filename_component(template_dir "${manifest}" DIRECTORY)
  if(NOT EXISTS "${template_dir}/${entry}")
    message(FATAL_ERROR "manifest entry does not exist: ${manifest} -> ${entry}")
  endif()
endforeach()

file(GLOB template_dirs LIST_DIRECTORIES true "${ROOT}/templates/*/*")
foreach(dir IN LISTS template_dirs)
  if(NOT IS_DIRECTORY "${dir}")
    continue()
  endif()
  if(NOT EXISTS "${dir}/template.manifest")
    message(FATAL_ERROR "template directory is not discoverable (missing manifest): ${dir}")
  endif()
endforeach()

file(GLOB_RECURSE examples LIST_DIRECTORIES false "${ROOT}/examples/*.zan")
foreach(example IN LISTS examples)
  file(RELATIVE_PATH rel "${ROOT}" "${example}")
  string(REPLACE "\\" "/" rel "${rel}")
  list(FIND refs "${rel}" ref_index)
  if(ref_index GREATER -1)
    continue()
  endif()
  string(FIND "${rel}" "examples/game/" game_prefix)
  if(game_prefix EQUAL 0)
    continue()
  endif()
  get_filename_component(example_dir "${example}" DIRECTORY)
  if(EXISTS "${example_dir}/README.md")
    continue()
  endif()
  file(READ "${example}" example_text)
  string(REGEX MATCH "^[ \t]*///|^[ \t]*//" has_comment "${example_text}")
  if(NOT has_comment)
    message(FATAL_ERROR "unregistered example has neither README.md nor opening comment: ${rel}")
  endif()
endforeach()
list(LENGTH manifests manifest_count)
message(STATUS "gallery coverage OK: ${entry_count} seed entries, ${manifest_count} manifests")
