# Generates a single object that bakes a directory of files into the executable
# as embedded resources, plus the tiny read API the runtime uses to pull them
# back out in memory. No self-extract, no external files: skins/DB drivers/other
# extension assets become part of the exe and are looked up by name at runtime.
#
#   zan_embed_read(name)        -> NUL-terminated bytes (text resources)
#   zan_embed_has(name)         -> 1/0
#   zan_embed_bytes(name,&len)  -> raw pointer + length (binary resources)
#   zan_embed_list(prefix)      -> '\n'-joined names with that prefix
#
# Only the data lives here; the read API is either the always-linked
# src\runtime\zan_embed_api.c or the copy zanc emits into a program that calls
# Skin.EmbedRead (src\compiler\embedres.c). This object is just linked in
# (--link-input) and hands its table over in a constructor.
#
# ONE object per program, carrying every resource group: zan_embed_register
# *replaces* the registered table (see embedres.c), so linking two generated
# objects means whichever constructor runs last hides the other's resources.
# Pass several groups with -Group instead of generating several objects.
param(
    # "<dir>=<prefix>" or "<dir>=<prefix>:<wildcard>", several separated by
    # ';' -- pass them as ONE argument, because `powershell -File` hands every
    # token to the next positional parameter instead of building an array:
    #   -Group "stdlib\Gui\skins=skins;src\ide_zan\assets=ide:*.css"
    [string[]]$Group = @(),
    [string]$Root = "",                            # single group: directory to embed
    [string]$Prefix = "",                          # single group: name prefix, e.g. "skins"
    [string]$Include = "",                         # single group: wildcard, e.g. "*.css"
                                                   # (default: every file under -Root)
    [Parameter(Mandatory=$true)][string]$OutC,     # generated .c path
    [string]$OutO = "",                            # if set, compile to this .o
    [string]$Clang = "clang"
)

$ErrorActionPreference = "Stop"

# Normalize both spellings into one list of {Root, Prefix, Include}.
$groups = @()
foreach ($g in ($Group | ForEach-Object { $_ -split ';' } |
                Where-Object { $_.Trim() -ne "" })) {
    $g = $g.Trim()
    $eq = $g.IndexOf('=')
    if ($eq -lt 1) { Write-Output "GEN_EMBED_BAD_GROUP=$g (want <dir>=<prefix>[:<wildcard>])"; exit 1 }
    $gRoot = $g.Substring(0, $eq)
    $rest = $g.Substring($eq + 1)
    $colon = $rest.IndexOf(':')
    if ($colon -ge 0) {
        $groups += [pscustomobject]@{ Root = $gRoot; Prefix = $rest.Substring(0, $colon); Include = $rest.Substring($colon + 1) }
    } else {
        $groups += [pscustomobject]@{ Root = $gRoot; Prefix = $rest; Include = "" }
    }
}
if ($Root -ne "") {
    if ($Prefix -eq "") { Write-Output "GEN_EMBED_NO_PREFIX"; exit 1 }
    $groups += [pscustomobject]@{ Root = $Root; Prefix = $Prefix; Include = $Include }
}
if ($groups.Count -eq 0) { Write-Output "GEN_EMBED_NO_INPUT (pass -Group or -Root/-Prefix)"; exit 1 }

# Every group's files, each tagged with the name it is embedded under.
$files = @()
foreach ($g in $groups) {
    $gRoot = (Resolve-Path $g.Root).Path
    if ($g.Include -ne "") {
        $found = Get-ChildItem $gRoot -Recurse -File -Filter $g.Include | Sort-Object FullName
    } else {
        $found = Get-ChildItem $gRoot -Recurse -File | Sort-Object FullName
    }
    foreach ($f in $found) {
        $rel = $f.FullName.Substring($gRoot.Length).TrimStart('\','/') -replace '\\','/'
        $files += [pscustomobject]@{ FullName = $f.FullName; EmbedName = "$($g.Prefix)/$rel" }
    }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* GENERATED by scripts/gen_embed.ps1 -- do not edit. */")
[void]$sb.AppendLine("#include <string.h>")
[void]$sb.AppendLine("#include <stdlib.h>")
[void]$sb.AppendLine("typedef unsigned char zan_u8;")
[void]$sb.AppendLine("typedef struct { const char* name; const zan_u8* data; long long len; } zan_embed_ent;")
[void]$sb.AppendLine("")

$names = @()
$idx = 0
foreach ($f in $files) {
    $name = $f.EmbedName
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    $len = $bytes.Length
    [void]$sb.AppendLine("/* $name ($len bytes) */")
    [void]$sb.Append("static const zan_u8 d$idx" + "[] = {")
    $line = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $len; $i++) {
        [void]$line.Append([string]$bytes[$i])
        [void]$line.Append(',')
        if ($line.Length -ge 110) { [void]$sb.AppendLine(); [void]$sb.Append($line.ToString()); [void]$line.Clear() }
    }
    if ($line.Length -gt 0) { [void]$sb.AppendLine(); [void]$sb.Append($line.ToString()) }
    # trailing NUL so text resources round-trip as C strings; len excludes it
    [void]$sb.AppendLine("0};")
    $names += [pscustomobject]@{ Name = $name; Idx = $idx; Len = $len }
    $idx++
}

[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const zan_embed_ent zan_embed_tbl[] = {")
foreach ($n in $names) {
    $esc = $n.Name -replace '\\','\\\\' -replace '"','\"'
    [void]$sb.AppendLine("  { `"$esc`", d$($n.Idx), $($n.Len) },")
}
[void]$sb.AppendLine("  { 0, 0, 0 }")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const long long zan_embed_cnt = $($names.Count);")
[void]$sb.AppendLine("")
# The read API lives in the always-linked runtime; this object only carries the
# data and hands it to the runtime registry before main runs.
[void]$sb.AppendLine(@"
extern void zan_embed_register(const zan_embed_ent* tbl, long long n);
__attribute__((constructor))
static void zan_embed_ctor(void){ zan_embed_register(zan_embed_tbl, zan_embed_cnt); }
"@)

$dir = Split-Path -Parent $OutC
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
[System.IO.File]::WriteAllText($OutC, $sb.ToString())
Write-Output "GEN_EMBED_C=$OutC files=$($names.Count)"

if ($OutO -ne "") {
    & $Clang --target=x86_64-w64-windows-gnu -O2 -c $OutC -o $OutO
    if ($LASTEXITCODE -ne 0) { Write-Output "GEN_EMBED_COMPILE_FAILED"; exit 1 }
    Write-Output "GEN_EMBED_O=$OutO"
}
