# Generates a single object that bakes a directory of files into the executable
# as embedded resources, plus the tiny read API the runtime uses to pull them
# back out in memory. No self-extract, no external files: skins/DB drivers/other
# extension assets become part of the exe and are looked up by name at runtime.
#
#   zan_embed_read(name)        -> NUL-terminated bytes (text resources)
#   zan_embed_has(name)         -> 1/0
#   zan_embed_bytes(name,&len)  -> raw pointer + length (binary resources)
#   zan_embed_list(prefix)      -> '\n'-joined names with that prefix
#
# The API and the data live in the same generated object, so nothing in the
# existing runtime needs editing; the object is just linked in (--link-input).
param(
    [Parameter(Mandatory=$true)][string]$Root,     # directory to embed
    [Parameter(Mandatory=$true)][string]$Prefix,   # logical name prefix, e.g. "skins"
    [Parameter(Mandatory=$true)][string]$OutC,     # generated .c path
    [string]$OutO = "",                            # if set, compile to this .o
    [string]$Clang = "clang"
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path $Root).Path
$files = Get-ChildItem $root -Recurse -File | Sort-Object FullName

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* GENERATED by scripts/gen_embed.ps1 -- do not edit. */")
[void]$sb.AppendLine("#include <string.h>")
[void]$sb.AppendLine("#include <stdlib.h>")
[void]$sb.AppendLine("typedef unsigned char zan_u8;")
[void]$sb.AppendLine("typedef struct { const char* name; const zan_u8* data; long long len; } zan_embed_ent;")
[void]$sb.AppendLine("")

$names = @()
$idx = 0
foreach ($f in $files) {
    $rel = $f.FullName.Substring($root.Length).TrimStart('\','/') -replace '\\','/'
    $name = "$Prefix/$rel"
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    $len = $bytes.Length
    [void]$sb.AppendLine("/* $name ($len bytes) */")
    [void]$sb.Append("static const zan_u8 d$idx" + "[] = {")
    $line = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $len; $i++) {
        [void]$line.Append([string]$bytes[$i])
        [void]$line.Append(',')
        if ($line.Length -ge 110) { [void]$sb.AppendLine(); [void]$sb.Append($line.ToString()); [void]$line.Clear() }
    }
    if ($line.Length -gt 0) { [void]$sb.AppendLine(); [void]$sb.Append($line.ToString()) }
    # trailing NUL so text resources round-trip as C strings; len excludes it
    [void]$sb.AppendLine("0};")
    $names += [pscustomobject]@{ Name = $name; Idx = $idx; Len = $len }
    $idx++
}

[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const zan_embed_ent zan_embed_tbl[] = {")
foreach ($n in $names) {
    $esc = $n.Name -replace '\\','\\\\' -replace '"','\"'
    [void]$sb.AppendLine("  { `"$esc`", d$($n.Idx), $($n.Len) },")
}
[void]$sb.AppendLine("  { 0, 0, 0 }")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const long long zan_embed_cnt = $($names.Count);")
[void]$sb.AppendLine("")
# The read API lives in the always-linked runtime; this object only carries the
# data and hands it to the runtime registry before main runs.
[void]$sb.AppendLine(@"
extern void zan_embed_register(const zan_embed_ent* tbl, long long n);
__attribute__((constructor))
static void zan_embed_ctor(void){ zan_embed_register(zan_embed_tbl, zan_embed_cnt); }
"@)

$dir = Split-Path -Parent $OutC
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
[System.IO.File]::WriteAllText($OutC, $sb.ToString())
Write-Output "GEN_EMBED_C=$OutC files=$($names.Count)"

if ($OutO -ne "") {
    & $Clang --target=x86_64-w64-windows-gnu -O2 -c $OutC -o $OutO
    if ($LASTEXITCODE -ne 0) { Write-Output "GEN_EMBED_COMPILE_FAILED"; exit 1 }
    Write-Output "GEN_EMBED_O=$OutO"
}
