# Build-time custom-component discovery.
#
# Scans a project source tree for component classes and regenerates the
# CustomComponents registry, so a new component file appears in the designer
# palette / JSON loader after a rebuild without any manual registration.
#
# A component is a `class X : Control` immediately preceded (allowing blank or
# doc-comment lines) by a marker line:
#
#     /// @component [Group] [icon]
#     class MyChart : Control { ... MyChart() { InitControl("MyChart", 5); } ... }
#
# Requirements for a discovered component:
#   * declares a no-argument constructor (so `new X()` works), and
#   * overrides Kind() to return its type tag (matching the class name is
#     recommended so JSON `type` and the class agree).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\scan_components.ps1 `
#       -Source components -Out stdlib\Gui\CustomComponents.zan

param(
    [string]$Source = "components",
    [string]$Out = "stdlib\Gui\CustomComponents.zan"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$comps = @()
$srcPath = Join-Path $root $Source
if (Test-Path $srcPath) {
    $files = Get-ChildItem -Path $srcPath -Recurse -Filter *.zan -ErrorAction SilentlyContinue
    foreach ($f in $files) {
        $lines = Get-Content -LiteralPath $f.FullName
        $ns = ""
        $pending = $false
        $pendGroup = "Custom"
        $pendIcon = ""
        for ($i = 0; $i -lt $lines.Count; $i++) {
            $ln = $lines[$i].Trim()
            if ($ln -match '^namespace\s+([A-Za-z0-9_.]+)') { $ns = $Matches[1] }
            if ($ln -match '@component(.*)$') {
                $rest = $Matches[1].Trim()
                $parts = @($rest -split '\s+' | Where-Object { $_ -ne "" })
                if ($parts.Count -ge 1) { $pendGroup = $parts[0] } else { $pendGroup = "Custom" }
                if ($parts.Count -ge 2) { $pendIcon = $parts[1] } else { $pendIcon = "" }
                $pending = $true
                continue
            }
            if ($pending -and $ln -match '^class\s+([A-Za-z0-9_]+)\s*:\s*Control\b') {
                $comps += [pscustomobject]@{
                    Name = $Matches[1]; Group = $pendGroup; Icon = $pendIcon; Namespace = $ns
                }
                $pending = $false
            } elseif ($pending -and $ln -match '^class\s') {
                $pending = $false
            }
        }
    }
}

$usings = @($comps | ForEach-Object { $_.Namespace } |
    Where-Object { $_ -ne "" -and $_ -ne "Gui" } | Sort-Object -Unique)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("using System;")
foreach ($u in $usings) { [void]$sb.AppendLine("using $u;") }
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace Gui;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("/// GENERATED by scripts/scan_components.ps1 - do not edit by hand.")
[void]$sb.AppendLine("/// Registry of project-defined custom components discovered at build time.")
[void]$sb.AppendLine("class CustomComponents {")

[void]$sb.AppendLine("    static List<string> Kinds() {")
[void]$sb.AppendLine("        List<string> k = new List<string>();")
foreach ($c in $comps) { [void]$sb.AppendLine("        k.Add(`"$($c.Name)`");") }
[void]$sb.AppendLine("        return k;")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("")

[void]$sb.AppendLine("    static string GroupOf(string kind) {")
foreach ($c in $comps) { [void]$sb.AppendLine("        if (kind == `"$($c.Name)`") { return `"$($c.Group)`"; }") }
[void]$sb.AppendLine("        return `"`";")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("")

[void]$sb.AppendLine("    static string IconOf(string kind) {")
foreach ($c in $comps) { [void]$sb.AppendLine("        if (kind == `"$($c.Name)`") { return `"$($c.Icon)`"; }") }
[void]$sb.AppendLine("        return `"`";")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("")

[void]$sb.AppendLine("    static Control Create(string kind) {")
foreach ($c in $comps) { [void]$sb.AppendLine("        if (kind == `"$($c.Name)`") { return new $($c.Name)(); }") }
[void]$sb.AppendLine("        return null;")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("}")

$outPath = Join-Path $root $Out
[System.IO.File]::WriteAllText($outPath, $sb.ToString())
Write-Output "SCAN_OK components=$($comps.Count) out=$Out"
